dist: xenial
sudo: required

language: go
go_import_path: github.com/src-d/google-cloud-dns-healthcheck
go:
  - 1.12.x

stages:
  - name: tests
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: tests
      name: 'Unit Tests'
      script:
        - make packages
        - make test
    - stage: release
      name: 'Release to GitHub and Docker Hub'
      script:
        - make packages
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
        on:
          all_branches: true
      after_deploy:
        - make docker-push-latest-release
